Fix InternalValidate Error caused by terraform-plugin-sdk update
Fixes #68

Error: InternalValidate

Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
* resource confluentcloud_kafka_cluster: deployment: TypeMap with Elem
*Resource not supported,use TypeList/TypeSet with Elem *Resource or TypeMap
with Elem *Schema